version: '2'
services:
  riak:
    restart: always
    container_name: crypto-riak-node
    image: crypto/riak
    build: docker/riak
    ports:
      - "8087:8087"   # Protobuffer port
      - "8093:8093"   # Yokodzuna port
      # Ports required for cluster
      - "4369:4369"
      - "8099:8099"
      - "6000-6005:6000-6005"
    env_file: .env
    volumes:
      - storage:/var/lib/riak
    networks:
      guroshnet0:
        ipv4_address: 188.0.0.19

  nginx-reverse:
    restart: always
    container_name: crypto-reverse-nginx
    image: crypto/nginx
    build: docker/nginx
    ports:
      - "8098:8098"
      - "8088:8088"
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    links:
      - riak
    networks:
      guroshnet0:
        ipv4_address: 188.0.0.18

volumes:
  storage:

networks:
  guroshnet0:
    external: true
    name: guroshnet

